package edu.virginia.vcgr.genii.client.rp;

/**
 * This is a common class for exceptions generated by the RP serialization and deserialization
 * process.
 * 
 * @author mmm2a
 */
public class ResourcePropertyException extends Exception
{
	static final long serialVersionUID = 0L;

	/**
	 * Create a new exception with a given message.
	 * 
	 * @param msg
	 *            The message that describes this exception.
	 */
	public ResourcePropertyException(String msg)
	{
		super(msg);
	}

	/**
	 * Create a new exception with a given message and child exception.
	 * 
	 * @param msg
	 *            The message that describes this exception.
	 * @param cause
	 *            A child exception that "caused" this exception to occur.
	 */
	public ResourcePropertyException(String msg, Throwable cause)
	{
		super(msg, cause);
	}
}
