/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_virginia_vcgr_genii_procmgmt_ProcessManager */

#ifndef _Included_edu_virginia_vcgr_genii_procmgmt_ProcessManager
#define _Included_edu_virginia_vcgr_genii_procmgmt_ProcessManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_virginia_vcgr_genii_procmgmt_ProcessManager
 * Method:    kill
 * Signature: (Ljava/lang/Process;)V
 */
JNIEXPORT void JNICALL Java_edu_virginia_vcgr_genii_procmgmt_ProcessManager_kill
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
