#!/bin/sh

# usage is connect-new-client <deployment name> <net connect URL>

usageExit()
{
	echo "usage is connect-new-container <deployment name> <net connect URL>"
	exit -1
}


# set install directory - by default, re-written by izpack (or you can set manually to test)
_INC_GENII_INSTALL_DIR="%{INSTALL_PATH}"
_INC_LOCAL_JAVA_DIR="$_INC_GENII_INSTALL_DIR/Java/linux-i586/jre"

# set vars for inputs
_DEPLOYMENT_NAME="$1"
_CONNECT_URL="$2"

if [ "x$_DEPLOYMENT_NAME" = "x" ]
then
	echo "Missing deployment name argument"
	usageExit
fi

if [ "x$_CONNECT_URL" = "x" ] 
then
	echo "Missing connect URL argument"
	usageExit
fi

# connect to net
echo connecting to $_CONNECT_URL...
"$_INC_GENII_INSTALL_DIR/grid" connect "$_CONNECT_URL" "$_DEPLOYMENT_NAME"
