#!/bin/sh

_GRID_GENII_INSTALL_DIR="%{INSTALL_PATH}"

if [ -z "$LD_LIBRARY_PATH" ]
then
	export LD_LIBRARY_PATH="%{INSTALL_PATH}/%{GENII_JNI_PATH}"
else
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:%{INSTALL_PATH}/%{GENII_JNI_PATH}"
fi

"$JAVA_HOME/bin/java" -Xms128M -Xmx512M -classpath "%{INSTALL_PATH}/lib:%{INSTALL_PATH}/ApplicationWatcher/app-manager.jar" -Dedu.virginia.vcgr.appwatcher.update-frequency=604800000 "-Dlog4j.configuration=%{LOG4JCONFIG}" "-Djava.library.path=%{INSTALL_PATH}/%{GENII_JNI_PATH}" "-Dedu.virginia.vcgr.genii.install-base-dir=%{INSTALL_PATH}" edu.virginia.vcgr.appmgr.launcher.ApplicationLauncher "%{INSTALL_PATH}/ApplicationWatcher/genii-client-application.properties" "$@"
