#!/bin/sh

# set install directory - by default, re-written by izpack (or you can set manually to test)
_INC_GENII_INSTALL_DIR="%{INSTALL_PATH}"
_INC_LOCAL_JAVA_DIR="$_INC_GENII_INSTALL_DIR/Java/linux-i586/jre"

# figure out name of host
# figure out port being used by container
# generate scripts to install container in init.d and start it on console
echo "Starting container in background and generating init.d script...  Use command $_INC_GENII_INSTALL_DIR/ext/JavaServiceWrapper/bin/UninstallContainerWrapper"
"$_INC_GENII_INSTALL_DIR/InstallContainerWrapper"

echo "install-new-container finished successfully"
exit 0
